# Default values for passculture.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gcp:
  # Project ID for the database where the data should be restored
  destProjectId: passculture-metier-ehp
  # Prefix of the secrets for the database where the data should be restored
  secretsNamePrefix: pcapi-staging

image:
  repository: europe-west1-docker.pkg.dev/passculture-infra-prod/pass-culture-tools/db-ops
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

schedule:  "0 3 * * 4" # Thursday at 3am

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: metier-production-sqldump@passculture-metier-prod.iam.gserviceaccount.com

configmap:
  ENV: staging
  NLTK_DATA: /root/nltk_data
  PROJECT_DEST: passculture-metier-ehp
  DUMP_BUCKET_NAME: passculture-metier-prod-europe-west1-sql-dump
  DUMP_FILENAME: dump.gz
  POSTGRES_SCRIPT_PATH: /scripts/anonymize.sql
  POSTGRES_INSTANCE_SRC: pcapi-production-9fb2eb30-replica-read0
  POSTGRES_INSTANCE_DEST: pcapi-ehp-0ef86e9a
  POSTGRES_DATABASE_SRC: pcapi-production
  POSTGRES_DATABASE_DEST: pcapi-staging
  POSTGRES_USER_DEST: pcapi-staging
  PC_API_ROOT_PATH: /usr/src/app
  IMPORT_USERS_SCRIPT_PATH: src/pcapi/scripts/beneficiary/import_users.py
  USERS_CSV_PATH: /scripts/data_pass-culture-api-staging.csv
  # dump_restore.sh feature flags
  EXPORT_DATA: true
  RECREATE_DEST_DATABASE: true
  IMPORT_DATA: true
  DELETE_DUMP_AFTER_IMPORT: true
  ANONYMISE_DEST: true
  CREATE_USERS: false
  POSTGRES_REMOVE_UNNEEDED_TABLES: true
  POSTGRES_UNNEEDED_TABLES : "activity user_session email"

destSecrets:
  - ADMINISTRATION_EMAIL_ADDRESS
  - ALGOLIA_API_KEY
  - ALGOLIA_APPLICATION_ID
  - ALLOCINE_API_KEY
  - PUBLIC_DATABASE_URL
  - DATABASE_ANONYMIZED_PASSWORD
  - DEMARCHES_SIMPLIFIEES_TOKEN
  - DEMARCHES_SIMPLIFIEES_WEBHOOK_TOKEN
  - DEV_EMAIL_ADDRESS
  - EXPORT_TOKEN
  - FLASK_SECRET
  - FTP_TITELIVE_PWD
  - FTP_TITELIVE_URI
  - FTP_TITELIVE_USER
  - JOUVE_API_DOMAIN
  - JOUVE_PASSWORD
  - JOUVE_USERNAME
  - JOUVE_VAULT_GUID
  - JWT_SECRET_KEY
  - MAILJET_API_KEY
  - MAILJET_API_SECRET
  - OVH_BUCKET_NAME
  - OVH_PASSWORD
  - OVH_REGION_NAME
  - OVH_TENANT_NAME
  - OVH_USER
  - PASS_CULTURE_BIC
  - PASS_CULTURE_IBAN
  - PASS_CULTURE_REMITTANCE_CODE
  - PAYMENTS_DETAILS_RECIPIENTS
  - PAYMENTS_REPORT_RECIPIENTS
  - PC_GOOGLE_KEY
  - PROVIDER_FNAC_BASIC_AUTHENTICATION_TOKEN
  - RECAPTCHA_SECRET
  - REDIS_URL
  - SENDINBLUE_API_KEY
  - SENTRY_DSN
  - SUPPORT_EMAIL_ADDRESS
  - TRANSACTIONS_RECIPIENTS
  - WALLET_BALANCES_RECIPIENTS
