# Default values for passculture.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gcp:
  # Project ID for the database where the data should be restored
  destProjectId: passculture-metier-ehp
  # Prefix of the secrets for the database where the data should be restored
  stagingSecretsNamePrefix: pcapi-staging
  perfSecretsNamePrefix: pcapi-perf

image:
  repository: europe-west1-docker.pkg.dev/passculture-infra-prod/pass-culture-tools/db-ops
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

schedule:  "0 3 * * 4" # Thursday at 3am
timezone: "Europe/Paris"

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

workflows:
  dump_restore: true
  post_process: false

serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: metier-production-sqldump@passculture-metier-prod.iam.gserviceaccount.com

configmap:
  NLTK_DATA: /root/nltk_data
  PROJECT_DEST: passculture-metier-ehp
  DUMP_BUCKET_NAME: passculture-metier-prod-europe-west1-sql-dump
  DUMP_FILENAME: dump.gz
  POSTGRES_INSTANCE_SRC: pcapi-production-9fb2eb30-replica-read0
  POSTGRES_DATABASE_SRC: pcapi-production

configmapStaging:
  ENV: staging
  POSTGRES_INSTANCE_DEST: pcapi-ehp-0ef86e9a
  POSTGRES_DATABASE_DEST: pcapi-staging
  POSTGRES_USER_DEST: pcapi-staging

configmapPerf:
  ENV: testing 
  POSTGRES_INSTANCE_DEST: pcapi-perf-1ac56766
  POSTGRES_DATABASE_DEST: pcapi-perf
  POSTGRES_USER_DEST: pcapi-perf

destSecrets:
  - ADMINISTRATION_EMAIL_ADDRESS
  - ALGOLIA_API_KEY
  - ALGOLIA_APPLICATION_ID
  - ALLOCINE_API_KEY
  - DATABASE_ANONYMIZED_PASSWORD
  - DEMARCHES_SIMPLIFIEES_TOKEN
  - DEMARCHES_SIMPLIFIEES_WEBHOOK_TOKEN
  - DEV_EMAIL_ADDRESS
  - EXPORT_TOKEN
  - FLASK_SECRET
  - FTP_TITELIVE_PWD
  - FTP_TITELIVE_URI
  - FTP_TITELIVE_USER
  - JOUVE_API_DOMAIN
  - JOUVE_PASSWORD
  - JOUVE_USERNAME
  - JOUVE_VAULT_GUID
  - JWT_SECRET_KEY
  - MAILJET_API_KEY
  - MAILJET_API_SECRET
  - OVH_BUCKET_NAME
  - OVH_PASSWORD
  - OVH_REGION_NAME
  - OVH_TENANT_NAME
  - OVH_USER
  - PASS_CULTURE_BIC
  - PASS_CULTURE_IBAN
  - PASS_CULTURE_REMITTANCE_CODE
  - PAYMENTS_DETAILS_RECIPIENTS
  - PAYMENTS_REPORT_RECIPIENTS
  - PC_GOOGLE_KEY
  - PROVIDER_FNAC_BASIC_AUTHENTICATION_TOKEN
  - PUBLIC_DATABASE_URL
  - RECAPTCHA_SECRET
  - REDIS_URL
  - SENDINBLUE_API_KEY
  - SENTRY_DSN
  - SUPPORT_EMAIL_ADDRESS
  - TRANSACTIONS_RECIPIENTS
  - WALLET_BALANCES_RECIPIENTS
