# Default values for passculture.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: europe-west1-docker.pkg.dev/passculture-infra-prod/pass-culture-tools/db-ops
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

schedule:  "0 3 * * 4" # Thursday at 3am
timezone: "Europe/Paris"

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

workflows:
  dump_restore: false
  post_process: true

serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: metier-production-sqldump@passculture-metier-prod.iam.gserviceaccount.com

instances:
  staging:
    secretsNamePrefix: pcapi-staging
    newUserPasswordSecretName: database_credentials_password
    postProcess: true
    envVars:
      ENV: staging
      SOURCE_INSTANCE: pcapi-production-9fb2eb30
      SOURCE_PROJECT: passculture-metier-prod
      SOURCE_USER: pcapi-production
      DEST_INSTANCE: pcapi-ehp-0ef86e9a
      DEST_PROJECT: passculture-metier-ehp
      DEST_NEW_USER: pcapi-staging
      DEST_INSTANCE_IP_ADDRESS_TYPE: public
    secrets:
      - STAGING_TEST_USER_PASSWORD
  perf:
    secretsNamePrefix: pcapi-perf
    newUserPasswordSecretName: database_credentials_password
    dependsOn: [staging]
    envVars:
      ENV: testing
      SOURCE_INSTANCE: pcapi-ehp-0ef86e9a
      SOURCE_PROJECT: passculture-metier-ehp
      SOURCE_USER: pcapi-staging
      DEST_INSTANCE: pcapi-perf-1ac56766
      DEST_PROJECT: passculture-metier-ehp
      DEST_NEW_USER: pcapi-perf
      DEST_INSTANCE_IP_ADDRESS_TYPE: public

commonEnvVars:
  NLTK_DATA: /root/nltk_data
  ANONYMIZE_SQL_SCRIPT_PATH: /scripts/anonymize.sql
  PCAPI_ROOT_PATH: /usr/src/app
  IMPORT_USERS_SCRIPT_PATH: src/pcapi/scripts/beneficiary/import_users.py
  USERS_CSV_PATH: /scripts/data_pass-culture-api-staging.csv
  TABLES_TO_EMPTY : "activity user_session email"
  DISABLE_VENUE_PROVIDERS: "true"

destSecrets:
  - ADMINISTRATION_EMAIL_ADDRESS
  - ALGOLIA_API_KEY
  - ALGOLIA_APPLICATION_ID
  - ALLOCINE_API_KEY
  - CLOUD_TASK_BEARER_TOKEN
  - DATABASE_ANONYMIZED_PASSWORD
  - DEMARCHES_SIMPLIFIEES_TOKEN
  - DEMARCHES_SIMPLIFIEES_WEBHOOK_TOKEN
  - DEV_EMAIL_ADDRESS
  - EXPORT_TOKEN
  - FLASK_SECRET
  - FTP_TITELIVE_PWD
  - FTP_TITELIVE_URI
  - FTP_TITELIVE_USER
  - JOUVE_API_DOMAIN
  - JOUVE_PASSWORD
  - JOUVE_USERNAME
  - JOUVE_VAULT_GUID
  - JWT_SECRET_KEY
  - MAILJET_API_KEY
  - MAILJET_API_SECRET
  - OVH_BUCKET_NAME
  - OVH_PASSWORD
  - OVH_REGION_NAME
  - OVH_TENANT_NAME
  - OVH_USER
  - PASS_CULTURE_BIC
  - PASS_CULTURE_IBAN
  - PASS_CULTURE_REMITTANCE_CODE
  - PAYMENTS_DETAILS_RECIPIENTS
  - PAYMENTS_REPORT_RECIPIENTS
  - PC_GOOGLE_KEY
  - PROVIDER_FNAC_BASIC_AUTHENTICATION_TOKEN
  - RECAPTCHA_SECRET
  - REDIS_URL
  - SENDINBLUE_API_KEY
  - SENTRY_DSN
  - SUPPORT_EMAIL_ADDRESS
  - TRANSACTIONS_RECIPIENTS
  - WALLET_BALANCES_RECIPIENTS
