version: 2.1
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.2
  slack: circleci/slack@4.2

###################
#  WORKFLOWS
###################

workflows:
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - run: echo "hey"
