---
client:
  hosts:
    - 127.0.0.1
  port: 10000
  http_auth: ${ELASTICSEARCH_AUTH}
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']