"""a revision

Revision ID: 6823fd2c784c
Revises: 5c5141274495
Create Date: 2021-07-16 14:03:55.038629

"""
# revision identifiers, used by Alembic.
revision = "6823fd2c784c"
down_revision = "5c5141274495"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
