"""Migrate idAtProvider Part 4

Revision ID: 9795938e641d
Revises: a080a657e4f5
Create Date: 2021-07-27 14:21:58.272991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9795938e641d'
down_revision = 'a080a657e4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("offer_idAtProviders_key", "offer", type="unique")
    op.drop_column("offer", "idAtProviders")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("offer", sa.Column("idAtProviders", sa.VARCHAR(length=70), autoincrement=False, nullable=True))
    op.create_unique_constraint("offer_idAtProviders_key", "offer", ["idAtProviders"])
    # ### end Alembic commands ###
