"""migrate_id_at_provider_part_4

Revision ID: 0382cc8aa04a
Revises: 61d5eed754c7
Create Date: 2021-05-17 09:56:17.219266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0382cc8aa04a"
down_revision = "61d5eed754c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("offer_idAtProviders_key", "offer", type_="unique")
    op.drop_column("offer", "idAtProviders")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("offer", sa.Column("idAtProviders", sa.VARCHAR(length=70), autoincrement=False, nullable=True))
    op.create_unique_constraint("offer_idAtProviders_key", "offer", ["idAtProviders"])
    # ### end Alembic commands ###
