"""Migrate idAtProvider Part 3

Revision ID: a080a657e4f5
Revises: 19b36a0b880a
Create Date: 2021-07-27 14:21:45.454702

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'a080a657e4f5'
down_revision = '19b36a0b880a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TABLE offer ADD CONSTRAINT "unique_idAtOfferProvider_and_venueId" UNIQUE USING INDEX "venueId_idAtProvider_index"'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_idAtOfferProvider_and_venueId", "offer", type="unique")
    # ### end Alembic commands ###
