"""add_isPhoneValidated_to_user

Revision ID: 22b38fe83d5a
Revises: ff04dc8fe18e
Create Date: 2021-04-28 12:44:22.449592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "22b38fe83d5a"
down_revision = "ff04dc8fe18e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column("user", sa.Column("isPhoneValidated", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column("user", "isPhoneValidated")
    # ### end Alembic commands ###
