"""create_booking_foreign_key_to_activation_code

Revision ID: 793f5d29dcf5
Revises: 40754eda1d0f
Create Date: 2021-04-21 15:14:45.267097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "793f5d29dcf5"
down_revision = "40754eda1d0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activation_code",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("expirationDate", sa.DateTime(), nullable=True),
        sa.Column("stockId", sa.BigInteger(), nullable=False),
        sa.Column("bookingId", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bookingId"],
            ["booking.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stockId"],
            ["stock.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activation_code_bookingId"), "activation_code", ["bookingId"], unique=False)
    op.create_index(op.f("ix_activation_code_stockId"), "activation_code", ["stockId"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activation_code_stockId"), table_name="activation_code")
    op.drop_index(op.f("ix_activation_code_bookingId"), table_name="activation_code")
    op.drop_table("activation_code")
    # ### end Alembic commands ###
