"""migrate_id_at_provider_part_3

Revision ID: 61d5eed754c7
Revises: e8199ef92975
Create Date: 2021-05-03 14:44:59.075035

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "61d5eed754c7"
down_revision = "e8199ef92975"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TABLE offer ADD CONSTRAINT "unique_idAtOfferProvider_and_venueId" UNIQUE USING INDEX "venueId_idAtProvider_index"'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_idAtOfferProvider_and_venueId", "offer", type_="unique")
    # ### end Alembic commands ###
