"""Removing dnBookedQuantity Column

Revision ID: 1edc71617854
Revises: 2ed5959876f1
Create Date: 2021-08-20 12:28:22.356026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1edc71617854"
down_revision = "2ed5959876f1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column("stock", "dnBookedQuantity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column("stock", sa.Column("dnBookedQuantity", sa.BigInteger(), nullable=False, server_default=sa.text("0")))
    # ### end Alembic commands ###
